name: run.yaml

on:
  push:
    branches: [master]

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - run: Rscript newsdata.R